# bounded_simulations.R
# Compare AGRAPA betting strategies for univariate [0,1]-bounded change detection.
#
# Data generating process
#   Pre-change:  Uniform(0, 1), mean = 0.5 = eta
#   Post-change: Beta(KAPPA*(0.5+delta), KAPPA*(0.5-delta))
#                mean = 0.5 + delta,  support = (0,1)
#                KAPPA = 4 → SD ≈ sqrt((0.25 - delta^2) / 5)
#
# Section A — main strategy comparison (5 strategies × 6 deltas)
#   Outputs: simulations/output/bounded_sim_results.csv
#
# Section B — window-size sensitivity (Window AGRAPA vs Per-clock, 4 W values)
#   Outputs: simulations/output/bounded_w_results.csv
#
# Section C — change-point location sensitivity (5 strategies × 6 deltas × 3 nu values)
#   Outputs: simulations/output/bounded_nu_results.csv
#   Hypothesis: Full AGRAPA degrades as nu grows (pre-change burns in the bet
#               towards eta), while windowed strategies adapt faster post-change.
#
# Figures are generated by ssc-2026/figures.R (reads all three CSVs).
#
# ── Timing (single core) ────────────────────────────────────────────────────
#   Section A: ~30 seconds   (N_REP=500, N=500, 6 deltas, 5 strategies)
#   Section B: ~90 seconds   (N_REP_W=300, N=500, 6 deltas, 4 W, 2 strategies)
#   Section C: ~75 seconds   (N_REP_C=300, N=500, 6 deltas, 3 nu, 5 strategies)
# ────────────────────────────────────────────────────────────────────────────

suppressPackageStartupMessages(library(multichangepoints))

# ── 0. Shared constants ───────────────────────────────────────────────────────

ETA     <- 0.5
KAPPA   <- 4            # Beta concentration parameter
ALPHA   <- 0.001
THRESH  <- 1 / ALPHA
NU      <- 50L
N       <- 500L
N_REP   <- 500L
N_REP_W <- 300L         # reps for W-sensitivity section (wider grid, fewer reps)
N_REP_C <- 300L         # reps for nu-sensitivity section
DELTAS  <- c(0.05, 0.10, 0.15, 0.20, 0.30, 0.40)
NU_VALUES <- c(10L, 50L, 200L)
WIN     <- 30L          # default window (main comparison)
RHO     <- 0.1
N_KELLY <- 500L

set.seed(20240526)

script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)),
                       error = function(e) "simulations")
out_dir <- file.path(script_dir, "output")

# ── 1. Single replication ─────────────────────────────────────────────────────

run_one_rep <- function(strategy, a_post, b_post, eta, nu, n, thresh) {
  x <- c(runif(nu, 0, 1), rbeta(n - nu, a_post, b_post))

  if (strategy$mode == "per_clock") {
    res <- run_sr_per_clock(x, strategy$model, threshold = thresh)
    tau <- if (res$alarm) res$stopping_time else Inf
  } else {
    inc <- compute_increments(TSM(strategy$model), x)
    res <- run_detector(ShiryaevRobertsDetector(alpha = ALPHA, criterion = "ARL"),
                        inc)
    tau <- res$stopping_time
  }

  fa    <- as.integer(is.finite(tau) && tau <= nu)
  det_  <- as.integer(is.finite(tau) && tau > nu)
  delay <- if (is.finite(tau) && tau > nu) as.numeric(tau - nu) else NA_real_
  c(false_alarm = fa, detected = det_, delay = delay)
}

# ── 2. Section A: main strategy comparison ────────────────────────────────────

make_strategies <- function(delta, eta, kappa) {
  a <- kappa * (0.5 + delta);  b <- kappa * (0.5 - delta)
  l_grid <- seq(0.001, 0.999, length.out = N_KELLY)
  p_grid <- dbeta(l_grid, a, b);  p_grid <- p_grid / sum(p_grid)
  kelly_lam <- compute_kelly_optimal_bet(l_grid, eta, p_i = p_grid)
  list(
    full   = list(name = "Full AGRAPA",
                  model = BoundedModel(eta, bets = AGRAPABet(window = Inf)),
                  mode = "sr"),
    window = list(name = sprintf("Window AGRAPA (W=%d)", WIN),
                  model = BoundedModel(eta, bets = AGRAPABet(window = WIN)),
                  mode = "sr"),
    ewma   = list(name = sprintf("EWMA (rho=%.2f)", RHO),
                  model = BoundedModel(eta, bets = EWMABet(rho = RHO)),
                  mode = "sr"),
    pc     = list(name = sprintf("Per-clock W=%d", WIN),
                  model = BoundedModel(eta, bets = AGRAPABet(window = WIN)),
                  mode = "per_clock"),
    oracle = list(name = "Oracle Kelly",
                  model = BoundedModel(eta, bets = FixedBet(lambda = kelly_lam)),
                  mode = "sr")
  )
}

cat(sprintf(
  "Section A: %d reps x %d deltas x 5 strategies\n", N_REP, length(DELTAS)))
cat(sprintf(
  "DGP: pre=Uniform(0,1), post=Beta(%.0f*(0.5+d), %.0f*(0.5-d)), eta=%.1f\n\n",
  KAPPA, KAPPA, ETA))

a_results <- vector("list", length(DELTAS) * 5L)
idx <- 0L

for (delta in DELTAS) {
  cat(sprintf("delta=%.2f ... ", delta)); flush.console()
  t0     <- proc.time()["elapsed"]
  a_post <- KAPPA * (0.5 + delta)
  b_post <- KAPPA * (0.5 - delta)
  strats <- make_strategies(delta, ETA, KAPPA)

  for (s in strats) {
    ts   <- proc.time()["elapsed"]
    reps <- replicate(N_REP, run_one_rep(s, a_post, b_post, ETA, NU, N, THRESH))
    ms   <- (proc.time()["elapsed"] - ts) * 1000 / N_REP
    idx  <- idx + 1L
    a_results[[idx]] <- data.frame(
      delta        = delta,
      strategy     = s$name,
      kelly_lam    = if (inherits(s$model@bets, "FixedBet"))
                       s$model@bets@lambda else NA_real_,
      power        = mean(reps["detected",    ]),
      FAR          = mean(reps["false_alarm", ]),
      CAD          = mean(reps["delay",       ], na.rm = TRUE),
      comp_time_ms = ms,
      stringsAsFactors = FALSE
    )
  }
  cat(sprintf("%.1f sec\n", proc.time()["elapsed"] - t0))
}

a_df <- do.call(rbind, a_results)
rownames(a_df) <- NULL
write.csv(a_df, file.path(out_dir, "bounded_sim_results.csv"), row.names = FALSE)
cat("\nSection A results saved.\n\n")

# ── 3. Section B: window-size sensitivity ─────────────────────────────────────

W_VALUES <- c(1L, 5L, 30L, 100L)

cat(sprintf(
  "Section B: %d reps x %d deltas x %d W-values x 2 strategies\n\n",
  N_REP_W, length(DELTAS), length(W_VALUES)))

b_results <- vector("list", length(W_VALUES) * 2L * length(DELTAS))
idx <- 0L

for (W in W_VALUES) {
  cat(sprintf("W = %3d: ", W)); flush.console()
  for (delta in DELTAS) {
    a_post <- KAPPA * (0.5 + delta)
    b_post <- KAPPA * (0.5 - delta)

    for (mode in c("sr", "per_clock")) {
      s <- list(
        name  = if (mode == "sr") sprintf("Window (W=%d)", W)
                else              sprintf("Per-clock (W=%d)", W),
        model = BoundedModel(ETA, bets = AGRAPABet(window = as.numeric(W))),
        mode  = mode
      )
      ts   <- proc.time()["elapsed"]
      reps <- replicate(N_REP_W,
                        run_one_rep(s, a_post, b_post, ETA, NU, N, THRESH))
      ms   <- (proc.time()["elapsed"] - ts) * 1000 / N_REP_W

      idx <- idx + 1L
      b_results[[idx]] <- data.frame(
        W             = W,
        delta         = delta,
        strategy_type = if (mode == "sr") "Window" else "Per-clock",
        strategy      = s$name,
        power         = mean(reps["detected",    ]),
        FAR           = mean(reps["false_alarm", ]),
        CAD           = mean(reps["delay",       ], na.rm = TRUE),
        comp_time_ms  = ms,
        stringsAsFactors = FALSE
      )
    }
  }
  cat("done\n")
}

b_df <- do.call(rbind, b_results)
rownames(b_df) <- NULL
write.csv(b_df, file.path(out_dir, "bounded_w_results.csv"), row.names = FALSE)
cat("Section B results saved.\n\n")

# ── 4. Section C: change-point location sensitivity ───────────────────────

cat(sprintf(
  "Section C: %d reps x %d deltas x %d nu values x 5 strategies\n\n",
  N_REP_C, length(DELTAS), length(NU_VALUES)))

c_results <- vector("list", length(NU_VALUES) * length(DELTAS) * 5L)
idx <- 0L

for (nu_val in NU_VALUES) {
  cat(sprintf("nu = %3d: ", nu_val)); flush.console()
  for (delta in DELTAS) {
    a_post <- KAPPA * (0.5 + delta)
    b_post <- KAPPA * (0.5 - delta)
    strats <- make_strategies(delta, ETA, KAPPA)

    for (s in strats) {
      ts   <- proc.time()["elapsed"]
      reps <- replicate(N_REP_C,
                        run_one_rep(s, a_post, b_post, ETA, nu_val, N, THRESH))
      ms   <- (proc.time()["elapsed"] - ts) * 1000 / N_REP_C
      idx  <- idx + 1L
      c_results[[idx]] <- data.frame(
        nu           = nu_val,
        delta        = delta,
        strategy     = s$name,
        kelly_lam    = if (inherits(s$model@bets, "FixedBet"))
                         s$model@bets@lambda else NA_real_,
        power        = mean(reps["detected",    ]),
        FAR          = mean(reps["false_alarm", ]),
        CAD          = mean(reps["delay",       ], na.rm = TRUE),
        comp_time_ms = ms,
        stringsAsFactors = FALSE
      )
    }
  }
  cat("done\n")
}

c_df <- do.call(rbind, c_results)
rownames(c_df) <- NULL
write.csv(c_df, file.path(out_dir, "bounded_nu_results.csv"), row.names = FALSE)
cat("Section C results saved.\n")
