# make_latex_tables.R
# Builds the LaTeX tables for Section 7.1 (joint detection) and the
# supplementary betting-strategy comparison (bounded_simulations.R, Section A).
# Reads existing simulation output CSVs -- does not re-run any simulations.
#
# Outputs:
#   simulations/output/joint_cad_table.tex     -- CAD by detector, K, sparsity, delta
#   simulations/output/bounded_strategy_table.tex -- CAD + comp. time by betting strategy

.pkg_root <- local({
  d <- normalizePath(getwd())
  while (!file.exists(file.path(d, "DESCRIPTION")) && d != dirname(d)) d <- dirname(d)
  d
})
out_dir <- file.path(.pkg_root, "simulations", "output")

esc_num <- function(x, digits) formatC(x, format = "f", digits = digits)

# ── 1. Joint-detection CAD table (Section 7.1) ──────────────────────────────
# Scope: p = 0 (IID), independent streams, both change-points (nu = 10 and
# nu = 1000) -- broader than joint_oracle_vs_bounded.png, which only shows
# nu = 1000. Rows are grouped by (K, sparsity) as before, with nu nested
# inside each block via multirow.

joint <- read.csv(file.path(out_dir, "joint_sim_results.csv"), stringsAsFactors = FALSE)
j <- subset(joint, p == 0 & independent == TRUE & delta > 0)

j$detector_label <- with(j, ifelse(
  detector == "oracle", "oracle",
  ifelse(detector == "misspec", "misspec",
  ifelse(detector == "bounded" & combine == "average", "bnd_avg",
  ifelse(detector == "bounded" & combine == "product", "bnd_prod", NA)))))

# Slice to a handful of representative delta values rather than the full
# 19-point grid. Target values are matched to the nearest point actually on
# the (log-spaced) simulation grid.
delta_targets <- c(0.01, 0.05, 0.2)
grid_deltas   <- sort(unique(j$delta))
delta_keep    <- vapply(delta_targets, function(t) grid_deltas[which.min(abs(grid_deltas - t))],
                        numeric(1))
j <- j[j$delta %in% delta_keep, ]

nu_order <- c(10L, 1000L)

blocks <- list(
  list(K = 2L,  sparse = TRUE,  label = "$K = 2$, sparse change"),
  list(K = 2L,  sparse = FALSE, label = "$K = 2$, dense change"),
  list(K = 10L, sparse = TRUE,  label = "$K = 10$, sparse change"),
  list(K = 10L, sparse = FALSE, label = "$K = 10$, dense change")
)

lines <- character(0)
lines <- c(lines,
  "% Auto-generated by simulations/make_latex_tables.R -- do not edit by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Conditional average delay (CAD) of the four joint detectors from Section~7.1,",
  sprintf("  at $\\delta \\approx$ %s,",
          paste(esc_num(delta_keep, 2), collapse = ", ")),
  "  for IID streams ($p=0$), independent streams, and both an early ($\\nu = 10$) and late",
  "  ($\\nu = 1000$) change-point; the $\\nu = 1000$ rows are the slice visualized in",
  "  Figure~\\ref{fig:joint-oracle-vs-bounded}. All detectors control the ARL at level",
  "  $1/\\alpha = 10000$; entries are averages over 300 replications, rounded to the",
  "  nearest integer.}",
  "\\label{tab:joint-cad}",
  "\\begin{tabular}{rr cccc}",
  "\\toprule",
  "$\\nu$ & $\\delta$ & Oracle & Misspecified & Bounded (avg.) & Bounded (prod.) \\\\",
  "\\midrule"
)

for (blk in blocks) {
  lines <- c(lines, sprintf("\\multicolumn{6}{l}{\\textbf{%s}} \\\\", blk$label))

  for (nu_val in nu_order) {
    sub <- j[j$K == blk$K & j$sparse == blk$sparse & j$nu == nu_val, ]
    sub <- sub[order(sub$delta), ]
    deltas <- sort(unique(sub$delta))

    for (i in seq_along(deltas)) {
      dl  <- deltas[i]
      row <- sub[sub$delta == dl, ]
      get_cad <- function(lab) {
        v <- row$CAD[row$detector_label == lab]
        if (length(v) == 0L || is.na(v)) "--" else esc_num(v, 0)
      }
      nu_cell <- if (i == 1L) sprintf("\\multirow{%d}{*}{%d}", length(deltas), nu_val) else ""
      lines <- c(lines, sprintf(
        "%s & %s & %s & %s & %s & %s \\\\",
        nu_cell, esc_num(dl, 2), get_cad("oracle"), get_cad("misspec"),
        get_cad("bnd_avg"), get_cad("bnd_prod")
      ))
    }
  }
  lines <- c(lines, "\\midrule")
}
lines[length(lines)] <- "\\bottomrule"   # replace trailing \midrule
lines <- c(lines, "\\end{tabular}", "\\end{table}")

writeLines(lines, file.path(out_dir, "joint_cad_table.tex"))
message("Wrote ", file.path(out_dir, "joint_cad_table.tex"), " (", nrow(j), " data rows, delta in {",
        paste(esc_num(delta_keep, 2), collapse = ", "), "}, nu in {",
        paste(nu_order, collapse = ", "), "})")

# ── 2. Betting-strategy CAD + computation-time table (bounded_simulations.R, Section A) ──

bnd <- read.csv(file.path(out_dir, "bounded_sim_results.csv"), stringsAsFactors = FALSE)

strat_levels <- c("Full AGRAPA", "Window AGRAPA (W=30)", "EWMA (rho=0.10)",
                  "Per-clock W=30", "Oracle Kelly")
strat_labels <- c("Full AGRAPA", "Window AGRAPA ($W=30$)", "EWMA ($\\rho=0.10$)",
                  "Per-clock ($W=30$)", "Oracle Kelly")
names(strat_labels) <- strat_levels

lines2 <- c(
  "% Auto-generated by simulations/make_latex_tables.R -- do not edit by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Conditional average delay (CAD) and per-replication computation time",
  "  for the five betting strategies compared in the bounded-mean simulation study,",
  "  as a function of the post-change mean shift $\\delta$.",
  "  Pre-change: $\\mathrm{Uniform}(0,1)$; post-change: $\\mathrm{Beta}(4(0.5+\\delta), 4(0.5-\\delta))$;",
  "  $\\eta = 0.5$, $\\nu = 50$, $N = 500$, $\\alpha = 0.001$; averages over 500 replications.}",
  "\\label{tab:bounded-strategy}",
  "\\begin{tabular}{l r rr}",
  "\\toprule",
  "Strategy & $\\delta$ & CAD & Comp.\\ time (ms) \\\\",
  "\\midrule"
)

for (sl in strat_levels) {
  sub <- bnd[bnd$strategy == sl, ]
  sub <- sub[order(sub$delta), ]
  n <- nrow(sub)
  for (i in seq_len(n)) {
    strat_cell <- if (i == 1L) sprintf("\\multirow{%d}{*}{%s}", n, strat_labels[[sl]]) else ""
    lines2 <- c(lines2, sprintf(
      "%s & %s & %s & %s \\\\",
      strat_cell, esc_num(sub$delta[i], 2), esc_num(sub$CAD[i], 1), esc_num(sub$comp_time_ms[i], 2)
    ))
  }
  lines2 <- c(lines2, "\\midrule")
}
lines2[length(lines2)] <- "\\bottomrule"   # replace trailing \midrule
lines2 <- c(lines2, "\\end{tabular}", "\\end{table}")

writeLines(lines2, file.path(out_dir, "bounded_strategy_table.tex"))
message("Wrote ", file.path(out_dir, "bounded_strategy_table.tex"), " (", nrow(bnd), " data rows)")

# ── 3. Localization: ARL and CAD by graph, propagation speed, and allowance
#      (localization_graph_simulations.R, Sections 4.3/5.3) ────────────────
# graph_key/graph_label mirror ssc-2026/figures.R's Section 12 mapping exactly
# (base R here instead of dplyr::case_when) so the table and the figures can
# never disagree about how hub_connected folds into the hub-spoke label.
# ARL comes from the has_change == FALSE rows (global null), CAD_total from
# the has_change == TRUE rows (propagation-on-a-graph alternative); the two
# are matched by (graph_key, speed, strategy).

loc <- read.csv(file.path(out_dir, "localization_graph_sim_results.csv"), stringsAsFactors = FALSE)

loc$graph_key <- ifelse(
  loc$graph_type == "hub_spoke" & loc$hub_connected == "disconnected", "hub_spoke_disc",
  ifelse(loc$graph_type == "hub_spoke" & loc$hub_connected == "line", "hub_spoke_line",
  loc$graph_type))

graph_keys   <- c("hub_spoke_disc", "hub_spoke_line", "fully_connected",
                  "linear", "clustered_linear")
graph_labels <- c("Hub-spoke (disconnected)", "Hub-spoke (line)",
                  "Fully connected", "Linear chain", "Clustered linear")
names(graph_labels) <- graph_keys

strat_order  <- c("oracle", "graph_correct", "graph_misspec", "uniform")
speed_order  <- c(fast = "Fast", slow = "Slow")

loc_arl <- subset(loc, has_change == FALSE)
loc_cad <- subset(loc, has_change == TRUE)

get_metric <- function(df, gk, sp, strat, col) {
  v <- df[[col]][df$graph_key == gk & df$speed == sp & df$strategy == strat]
  if (length(v) == 0L || is.na(v)) "--" else esc_num(v, 1)
}

lines3 <- c(
  "% Auto-generated by simulations/make_latex_tables.R -- do not edit by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Global average run length (ARL) under the null and total conditional average",
  "  delay (CAD) under the propagation-on-a-graph alternative (Section~4.3), for the four",
  "  spending allowances of Section~5.3 in the $K = 24$ localization simulation, across five",
  "  graph topologies and both propagation speeds. Uniform is the $\\zeta = 0$ Bonferroni",
  "  baseline; Graph (correct) and Graph (mis-spec.) are adaptive spending on the true and",
  "  mis-specified proximity graph, respectively. All strategies control the global ARL at",
  "  $1/\\alpha = 1000$; entries are averages over 300 replications.}",
  "\\label{tab:localization}",
  "\\resizebox{\\textwidth}{!}{%",
  "\\begin{tabular}{l cccc cccc}",
  "\\toprule",
  "& \\multicolumn{4}{c}{ARL} & \\multicolumn{4}{c}{CAD} \\\\",
  "\\cmidrule(lr){2-5} \\cmidrule(lr){6-9}",
  "Propagation & Oracle & Graph (correct) & Graph (mis-spec.) & Uniform",
  "  & Oracle & Graph (correct) & Graph (mis-spec.) & Uniform \\\\",
  "\\midrule"
)

for (gk in graph_keys) {
  lines3 <- c(lines3,
    sprintf("\\multicolumn{9}{l}{\\textbf{%s}} \\\\", graph_labels[[gk]]),
    "\\midrule")

  for (sp in names(speed_order)) {
    arl_vals <- sapply(strat_order, function(s) get_metric(loc_arl, gk, sp, s, "ARL"))
    cad_vals <- sapply(strat_order, function(s) get_metric(loc_cad, gk, sp, s, "CAD_total"))
    lines3 <- c(lines3, sprintf(
      "%s & %s & %s & %s & %s & %s & %s & %s & %s \\\\",
      speed_order[[sp]],
      arl_vals[1], arl_vals[2], arl_vals[3], arl_vals[4],
      cad_vals[1], cad_vals[2], cad_vals[3], cad_vals[4]
    ))
  }
  lines3 <- c(lines3, "\\addlinespace")
}
lines3[length(lines3)] <- "\\bottomrule"   # replace trailing \addlinespace
lines3 <- c(lines3, "\\end{tabular}}", "\\end{table}")

writeLines(lines3, file.path(out_dir, "localization_table.tex"))
message("Wrote ", file.path(out_dir, "localization_table.tex"), " (", nrow(loc), " data rows)")
